# Generated by Django 2.2.10 on 2021-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.TextField()),
            ],
        ),
    ]
