# Generated by Django 2.2.10 on 2021-02-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdevice', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='order',
        ),
    ]
