# Generated by Django 2.2.10 on 2021-05-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdevice', '0003_remove_simulation_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
